protected/models/Client.php
<?php

/**
 * This is the model class for table "client".
 *
 * The followings are the available columns in table 'client':
 * @property integer $id
 * @property string $code
 * @property integer $correlative
 * @property string $name
 * @property string $phone
 * @property string $mobil
 * @property string $address
 * @property string $conctact
 * @property string $email
 * @property string $logo
 * @property integer $id_cli_type
 * @property integer $id_city
 * @property integer $r_c_u
 * @property string $r_c_d
 * @property string $r_c_i
 * @property string $r_c_o
 * @property string $r_c_f
 * @property integer $r_u_u
 * @property string $r_u_d
 * @property string $r_u_i
 * @property string $r_u_o
 * @property string $r_u_f
 * @property integer $r_d_u
 * @property string $r_d_d
 * @property string $r_d_i
 * @property integer $r_d_s
 * @property string $r_d_o
 * @property string $r_d_f
 * @property string $r_d_m
 *
 * The followings are the available model relations:
 * @property CliData[] $cliDatas
 * @property CliType $idCliType
 * @property City $idCity
 * @property Department[] $departments
 * @property Order[] $orders
 * @property SisUsuario[] $sisUsuarios
 * @property ZoneClient[] $zoneClients
 */
class Client extends GS3CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'client';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('code, name, address, id_city, correlative', 'required'),
			array('correlative, id_cli_type, id_city, r_c_u, r_u_u, r_d_u, r_d_s', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>25),
			array('name, mobil, conctact, email, logo, r_c_i, r_c_o, r_c_f, r_u_i, r_u_o, r_u_f, r_d_i, r_d_o, r_d_f, r_d_m', 'length', 'max'=>255),
			array('phone', 'length', 'max'=>15),
			array('r_c_d, r_u_d, r_d_d', 'safe'),
                        array('email','email'),
                        array('logo', 'file', 'allowEmpty' => TRUE, 'types'=>'jpg, gif, jpeg, png',
                            'maxSize'=> 5120000, 
                            'maxFiles'=> 1, 
                            'tooLarge'=> Yii::t('app', 'ERROR_FILE_SIZE_500KB'),
                            'wrongMimeType'=> YII::t('app', 'ERROR_FILE_SIZE_TYPE_IMAGEN')
                        ),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, code, correlative, name, phone, mobil, address, conctact, email, logo, id_cli_type, id_city, r_c_u, r_c_d, r_c_i, r_c_o, r_c_f, r_u_u, r_u_d, r_u_i, r_u_o, r_u_f, r_d_u, r_d_d, r_d_i, r_d_s, r_d_o, r_d_f, r_d_m', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'cliDatas' => array(self::HAS_MANY, 'CliData', 'id_client'),
			'idCliType' => array(self::BELONGS_TO, 'CliType', 'id_cli_type'),
			'idCity' => array(self::BELONGS_TO, 'City', 'id_city'),
			'departments' => array(self::HAS_MANY, 'Department', 'id_client'),
			'orders' => array(self::HAS_MANY, 'Order', 'id_client'),
			'sisUsuarios' => array(self::HAS_MANY, 'SisUsuario', 'id_client'),
			'zoneClients' => array(self::HAS_MANY, 'ZoneClient', 'id_client'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => Yii::t('app','ID'),
			'code' => Yii::t('app','Code'),
			'correlative' => Yii::t('app','Correlative'),
			'name' => Yii::t('app','Name'),
			'phone' => Yii::t('app','Phone'),
			'mobil' => Yii::t('app','Mobil'),
			'address' => Yii::t('app','Address'),
			'conctact' => Yii::t('app','Conctact'),
			'email' => Yii::t('app','Email'),
			'logo' => Yii::t('app','Logo'),
			'id_cli_type' => Yii::t('app','Id Cli Type'),
			'id_city' => Yii::t('app','Id City'),
			'r_c_u' => Yii::t('app','R C U'),
			'r_c_d' => Yii::t('app','R C D'),
			'r_c_i' => Yii::t('app','R C I'),
			'r_c_o' => Yii::t('app','R C O'),
			'r_c_f' => Yii::t('app','R C F'),
			'r_u_u' => Yii::t('app','R U U'),
			'r_u_d' => Yii::t('app','R U D'),
			'r_u_i' => Yii::t('app','R U I'),
			'r_u_o' => Yii::t('app','R U O'),
			'r_u_f' => Yii::t('app','R U F'),
			'r_d_u' => Yii::t('app','R D U'),
			'r_d_d' => Yii::t('app','R D D'),
			'r_d_i' => Yii::t('app','R D I'),
			'r_d_s' => Yii::t('app','R D S'),
			'r_d_o' => Yii::t('app','R D O'),
			'r_d_f' => Yii::t('app','R D F'),
			'r_d_m' => Yii::t('app','R D M'),
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('code',$this->code,true);
		$criteria->compare('correlative',$this->correlative);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('phone',$this->phone,true);
		$criteria->compare('mobil',$this->mobil,true);
		$criteria->compare('address',$this->address,true);
		$criteria->compare('conctact',$this->conctact,true);
		$criteria->compare('email',$this->email,true);
		$criteria->compare('logo',$this->logo,true);
		$criteria->compare('id_cli_type',$this->id_cli_type);
		$criteria->compare('id_city',$this->id_city);
		$criteria->compare('r_c_u',$this->r_c_u);
		$criteria->compare('r_c_d',$this->r_c_d,true);
		$criteria->compare('r_c_i',$this->r_c_i,true);
		$criteria->compare('r_c_o',$this->r_c_o,true);
		$criteria->compare('r_c_f',$this->r_c_f,true);
		$criteria->compare('r_u_u',$this->r_u_u);
		$criteria->compare('r_u_d',$this->r_u_d,true);
		$criteria->compare('r_u_i',$this->r_u_i,true);
		$criteria->compare('r_u_o',$this->r_u_o,true);
		$criteria->compare('r_u_f',$this->r_u_f,true);
		$criteria->compare('r_d_u',$this->r_d_u);
		$criteria->compare('r_d_d',$this->r_d_d,true);
		$criteria->compare('r_d_i',$this->r_d_i,true);
		$criteria->compare('r_d_s',$this->r_d_s);
		$criteria->compare('r_d_o',$this->r_d_o,true);
		$criteria->compare('r_d_f',$this->r_d_f,true);
		$criteria->compare('r_d_m',$this->r_d_m,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Client the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/ClientController.php
<?php

class ClientController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column1';
    private $file = '';
    private $data = array();

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' 
                'actions' => array('index'),
                'roles' => array('ClientActionIndex'),
            ),
            array('allow', // allow all users to perform 'view' 
                'actions' => array('view'),
                'roles' => array('ClientActionView'),
            ),
            array('allow', // allow all users to perform 'create' 
                'actions' => array('create'),
                'roles' => array('ClientActionCreate'),
            ),
            array('allow', // allow all users to perform 'update' 
                'actions' => array('update'),
                'roles' => array('ClientActionUpdate'),
            ),
            array('allow', // allow all users to perform 'admin' 
                'actions' => array('admin'),
                'roles' => array('ClientActionAdmin'),
            ),
            array('allow', // allow all users to perform 'delete' 
                'actions' => array('delete'),
                'roles' => array('ClientActionDelete'),
            ),
            array('allow', // allow all users to perform 'update' 
                'actions' => array('upload', 'saveUpload', 'processFileExcel'),
                'roles' => array('ClientActionUpload'),
            ),
            array('allow', // allow all users to perform 'delete' 
                'actions' => array('getClientLists'),
                'roles' => array('ClientActionClientLists'),
            ),
            array('allow', // allow all users to perform 'delete' 
                'actions' => array('getIdFromFullName'),
                'roles' => array('ClientActiongetIdFromFullName'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new Client;
        $model2 = new VZoneClient('search');
        $model2->unsetAttributes();  // clear any default values

        if (isset($_GET['VZoneClient']))
            $model2->attributes = $_GET['VZoneClient'];

        // Uncomment the following line if AJAX validation is needed
        $this->performAjaxValidation($model);

        if (isset($_POST['Client'])) {
            try {
                $model->attributes = $_POST['Client'];
                $Image = CUploadedFile::getInstance($model, 'logo');
                $model->r_c_o = 'form';
                if (!empty($Image)) {
                    $model->logo = $this->generateRandomString(5) . '-' . $this->url_slug($Image->name) . '.' . $Image->getExtensionName();
                    $Image->saveAs(Yii::getPathOfAlias('webroot') . Yii::app()->params['URL_CLIENT_LOGO'] . $model->logo);
                }
                if ($model->save()) {
                    if (Yii::app()->user->getState('CLIENT')->CLIENT_CREATE_SEND_EMAIL == 'true') {
                        $from = Yii::app()->user->nombre . '<' . Yii::app()->user->email . '>';
                        $subject = Yii::t('json', 1013, ['{codigo}' => $model->code, '{nombre}' => $model->name]);
                        $ok = Yii::t('email', 'Email-2004', array('{grupo}' => Yii::app()->user->getState('CLIENT')->CLIENT_CREATE_SEND_EMAIL_GROUP));
                        $error = Yii::t('email', 'Email-5003');
                        $this->layout = 'mail';
                        $msg = $this->render('../mail/client', ['model' => $model], true);
                        $to = $this->getEmailsListByPerfil(Yii::app()->user->getState('CLIENT')->CLIENT_CREATE_SEND_EMAIL_GROUP);
                        $this->sendEmail($from, $to, $subject, $msg, $ok, $error);
                    }
                    $this->saveData($model);
                    Yii::app()->user->setFlash('success', Yii::t('app', 'SUCCESS_CREATE_OK', array('{info}' => Yii::t('app', 'Client'))));
                    $this->redirect(array('update', 'id' => $model->id));
                } else {
                    Yii::app()->user->setFlash('danger', Yii::t('app', 'SUCCESS_CREATE_ERROR', array('{info}' => Yii::t('app', 'Client'))));
                }
            } catch (Exception $e) {
                if ($e->getCode() === 23000) {
                    Yii::app()->user->setFlash('danger', Yii::t('json', 5020, [
                                '{code}' => Yii::app()->request->getPost('Client')['code'],
                                '{correlativo}' => Yii::app()->request->getPost('Client')['correlative']
                                    ]
                    ));
                } else {
                    Yii::app()->user->setFlash('danger', $e->getCode() . ' ' . $e->getMessage());
                }
            }
        }

        $this->render('create', array(
            'model' => $model,
            'model2' => $model2,
            'City' => BsHtml::listData(City::model()->findAll('r_d_s=1'), 'id', 'name'),
            'attr' => $this->render_filelds(ClientField::model()->findAll('r_d_s=1')),
        ));
    }

    /**
     * Save/update Cli_data from prodduct
     * @author Giovanni Ariza <sistemas@giosyst3m.net>
     * @since 1.0.0 
     * @param model $model
     */
    public function saveData($model) {
        CliData::model()->deleteAll('id_client=' . $model->id);
        if (isset($_POST['car'])) {
            $value = array_values($_POST['car']);
            $key = array_keys($_POST['car']);
            for ($index = 0; $index < count($value); $index++) {
                if (!empty($key[$index])) {
                    $modelCara = new CliData();
                    $modelCara->id_client = $model->id;
                    $modelCara->id_field_client = $key[$index];
                    if (is_array($value[$index])) {
                        $modelCara->value = implode(',', $value[$index]);
                    } else {
                        $modelCara->value = $value[$index];
                    }
                    $modelCara->r_c_o = 'form';
                    $modelCara->save();
                }
            }
        }
        if (isset($_FILES['car']) && !empty($_FILES['car'])) {
            $files = $_FILES['car'];
            $key = array_keys($files['name']);
            for ($index = 0; $index < count($key); $index++) {
                if (!empty($files['name'][$key[$index]])) {
                    $modelCara = new CliData();
                    $modelCara->id_client = $model->id;
                    $modelCara->id_field_client = $key[$index];
                    $modelCara->value = $this->generateRandomString(5) . '-' . $this->url_slug($files['name'][$key[$index]]);
                    move_uploaded_file($files['tmp_name'][$key[$index]], Yii::getPathOfAlias('webroot') . Yii::app()->params['URL_CLIENTE_FILE'] . $modelCara->value);
                    $modelCara->r_c_o = 'form';
                    $modelCara->save();
                }
            }
        }
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model7 = new Order('search');
        $model7->unsetAttributes();  // clear any default values
        $model7->id_client = $id;
        if (isset($_GET['Order']))
            $model7->attributes = $_GET['Order'];

        $model3 = new ZoneClient;
        $model4 = new ZoneClient('search');
        $model4->unsetAttributes();  // clear any default values
        $model4->id_client = $id;
        if (isset($_GET['ZoneClient']))
            $model4->attributes = $_GET['ZoneClient'];

        // Uncomment the following line if AJAX validation is needed
        $this->performAjaxValidation($model3);

        if (isset($_POST['ZoneClient'])) {
            try {
                $model3->attributes = $_POST['ZoneClient'];
                $model3->id_client = $id;
                if ($model3->save()) {
                    Yii::app()->user->setFlash('success', Yii::t('app', 'SUCCESS_CREATE_OK', array('{info}' => Yii::t('app', 'ZoneClient'))));
                    $this->redirect(array('update', 'id' => $id));
                } else {
                    Yii::app()->user->setFlash('danger', Yii::t('app', 'SUCCESS_CREATE_ERROR', array('{info}' => Yii::t('app', 'ZoneClient'))));
                }
            } catch (Exception $e) {
                if ($e->getCode() === 23000) {
                    Yii::app()->user->setFlash('danger', Yii::t('json', 5007));
                } else {
                    Yii::app()->user->setFlash('danger', $e->getCode() . ' ' . $e->getMessage());
                }
            }
        }

        $model = $this->loadModel($id);

protected/views/client/_form.php
<?php
/* @var $this ClientController */
/* @var $model Client */
/* @var $form BSActiveForm */
?>

<?php
$form = $this->beginWidget('bootstrap.widgets.BsActiveForm', array(
    'id' => 'client-form',
    // Please note: When you enable ajax validation, make sure the corresponding
    // controller action is handling ajax validation correctly.
    // There is a call to performAjaxValidation() commented in generated controller code.
    // See class documentation of CActiveForm for details on this.
    'enableAjaxValidation' => true,
    'layout' => BsHtml::FORM_LAYOUT_HORIZONTAL,
    'htmlOptions' => array('enctype' => 'multipart/form-data'),
    'clientOptions' => array(
        'validateOnSubmit' => true,
    ),
    'htmlOptions' => array('enctype' => 'multipart/form-data','onsubmit'=>'return validateForm();',)
        ));
?>

<p class="help-block"> <?php echo Yii::t('app', 'Fields with'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'are required.') ?></p>
<div class="row">
    <div class="col-lg-6 col-med-6 col-xs-12 col-sm-12">
        <?php echo $form->errorSummary($model); ?>
        <?php echo $form->textFieldControlGroup($model, 'code', array('maxlength' => 15)); ?>
        <?php echo $form->textFieldControlGroup($model, 'correlative', array('maxlength' => 15,'help'=> 'Colcar 0 cuando sea la principal<br>Colocar mayor 1 cuando se una sucursal')); ?>
        <?php echo $form->textFieldControlGroup($model, 'name', array('maxlength' => 255)); ?>
        <?php echo $form->textFieldControlGroup($model, 'phone', array('maxlength' => 15)); ?>
        <?php echo $form->textFieldControlGroup($model, 'mobil', array('maxlength' => 255)); ?>
        <?php echo $form->textAreaControlGroup($model, 'address', array('rows' => 6)); ?>
        <?php echo $form->dropDownListControlGroup($model,'id_city',$City,array('data-style'=>'btn-primary','class'=>'selectpicker show-tick','empty'=>'Select one','data-live-search'=>true,)); ?>
        <?php echo $form->textFieldControlGroup($model, 'conctact', array('maxlength' => 255)); ?>
        <?php echo $form->textFieldControlGroup($model, 'email', array('maxlength' => 255)); ?>
        <?php echo $form->fileFieldControlGroup($model, 'logo'); ?>

        <?php
        if (!empty($model->logo)) {
            echo '<div class="center-block text-center">';
            echo $model->ShowImagen($model->logo, Yii::app()->params['URL_CLIENT_LOGO']);
            echo '</div><div class="clearfix">&nbsp;</div>';
        }
        ?>
        <?php
        if (Yii::app()->user->checkAccess('ClientCreateStatusChange') || Yii::app()->user->checkAccess('ClientUpdateStatusChange')) {
            echo $form->dropDownListControlGroup($model, 'r_d_s', array(1 => 'Activo', 0 => 'Inactivo'), array('data-style' => 'btn-info', 'class' => 'selectpicker show-tick'));
        }
        ?>  
    </div>
    <div id="proAttr" class="col-lg-6 col-med-6 col-xs-12 col-sm-12">
        <h3><?php echo Yii::t('app','Caracteristic');?></h3>
        <?php echo $attr; ?>
    </div>
      <?php
        if (Yii::app()->user->checkAccess('ClientCreateButtonSave') || Yii::app()->user->checkAccess('ClientUpdateButtonSave')) {
            echo BsHtml::submitButton(yii::t('app', 'Submit'), array('color' => BsHtml::BUTTON_COLOR_PRIMARY));
        }
        ?>    
        <?php
        if (Yii::app()->user->checkAccess('ClientCreateButtonNew') || Yii::app()->user->checkAccess('ClientUpdateButtonNew')) {
            echo BsHtml::link(Yii::t('app', 'New'), Yii::app()->createAbsoluteUrl('Client/create'), array('class' => 'btn btn-primary'));
        }
        ?>  
</div>
<?php $this->endWidget(); ?>

protected/views/client/_result_excel.php
<?php

$this->widget('bootstrap.widgets.BsGridView', array(
	'dataProvider' => $arrayDataProvider,
	'columns' => array(
            'id',
		array(
			'name' => 'A',
			'type' => 'raw',
			'value' => 'CHtml::encode($data["A"])'
		),
		array(
			'name' => 'B',
			'type' => 'raw',
			'value' => 'CHtml::encode($data["B"])'
		),
		array(
			'name' => 'C',
			'type' => 'raw',
			'value' => 'CHtml::encode($data["C"])'
		),
		array(
			'name' => 'D',
			'type' => 'raw',
			'value' => 'CHtml::encode($data["D"])'
		),
		array(
			'name' => 'E',
			'type' => 'raw',
			'value' => 'CHtml::encode($data["E"])'
		),
		array(
			'name' => 'F',
			'type' => 'raw',
			'value' => 'CHtml::encode($data["F"])'
		),
		array(
			'name' => 'G',
			'type' => 'raw',
			'value' => 'CHtml::encode($data["G"])'
		),
		array(
			'name' => 'H',
			'type' => 'raw',
			'value' => 'CHtml::encode($data["H"])'
		),
		array(
			'name' => 'I',
			'type' => 'raw',
			'value' => 'CHtml::encode($data["I"])'
		),
		array(
			'name' => 'J',
			'type' => 'raw',
			'value' => 'CHtml::encode($data["J"])'
		),
		array(
			'name' => 'K',
			'type' => 'raw',
			'value' => 'CHtml::encode($data["K"])'
		),
		array(
			'name' => 'L',
			'type' => 'raw',
			'value' => 'CHtml::encode($data["L"])'
		),
		array(
			'name' => 'M',
			'type' => 'raw',
			'value' => 'CHtml::encode($data["M"])'
		),
		array(
			'name' => 'N',
			'type' => 'raw',
			'value' => 'CHtml::encode($data["N"])'
		),
		array(
			'name' => 'O',
			'type' => 'raw',
			'value' => 'CHtml::encode($data["O"])'
		),
		array(
			'name' => 'P',
			'type' => 'raw',
			'value' => 'CHtml::encode($data["P"])'
		),
		array(
			'name' => 'Resultado',
			'type' => 'raw',
			'value' => '$data["result"]'
		),	
),
           'type' => BsHtml::GRID_TYPE_CONDENSED 
    . ' ' . BsHtml
    ::GRID_TYPE_BORDERED . ' ' . BsHtml
    ::GRID_TYPE_STRIPED  
));

protected/views/client/_upload.php
<form>
    <?php
    $this->widget('ext.EAjaxUpload.EAjaxUpload', array(
        'id' => 'uploadFile',
        'config' => array(
            'action' => Yii::app()->createUrl('client/saveUpload'),
            'allowedExtensions' => array("xls", 'xlsx'), //array("jpg","jpeg","gif","exe","mov" and etc...
            'sizeLimit' => Yii::app()->user->getState('FILE')->FILES_UPLOAD_MAX, // maximum file size in bytes
//               'minSizeLimit'=>10*1024*1024,// minimum file size in bytes
            'onComplete' => "js:function(id, fileName, responseJSON){ processExcelFile(responseJSON); }",
            'messages' => array(
                'typeError' => "{file} has invalid extension. Only {extensions} are allowed. GIO",
                'sizeError' => "{file} is too large, maximum file size is {sizeLimit}.",
                'minSizeError' => "{file} is too small, minimum file size is {minSizeLimit}.",
                'emptyError' => "{file} is empty, please select files again without it.",
                'onLeave' => "The files are being uploaded, if you leave now the upload will be cancelled."
            ),
            'showMessage' => "js:function(message){ alert(message); }"
        )
    ));
    ?>

</form>
<div class="result"></div>

protected/views/client/admin.php
<?php
/* @var $this ClientController */
/* @var $model Client */


$this->breadcrumbs = array(
    'Clients' => array('index'),
    'Manage',
);

$this->menu = array(
    array('icon' => 'glyphicon glyphicon-list', 'label' => 'List Client', 'url' => array('index')),
    array('icon' => 'glyphicon glyphicon-plus-sign', 'label' => 'Create Client', 'url' => array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#client-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>


<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo BsHtml::button(Yii::t('app', 'Advanced search'), array('class' => 'search-button', 'icon' => BsHtml::GLYPHICON_SEARCH, 'color' => BsHtml::BUTTON_COLOR_PRIMARY), '#'); ?></h3>
    </div>
    <div class="panel-body">
        <p>
            <?php echo Yii::t('app', 'You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>
                &lt;&gt;</b>
            or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.'); ?>        </p>

        <div class="search-form" style="display:none">
            <?php
//            $this->renderPartial('_search', array(
//                'model' => $model2,
//            ));
            ?>
        </div>
        <!-- search-form -->

        <?php
        $this->widget('bootstrap.widgets.BsGridView', array(
            'id' => 'client-grid',
            'dataProvider' => $model2->search(),
            'filter' => $model2,
            'type' => BsHtml::GRID_TYPE_RESPONSIVE,
            'columns' => array(
                'code',
                'correlative',
                'name',
                'city',
                'zone',
                array(
                    'name' => 'client_r_d_s',
                    'value' => '$data->RegistroEstado($data->client_r_d_s)',
                    'filter' => array(0 => 'Inactivo', 1 => 'Activo')
                ),
                array(
                    'class' => 'bootstrap.widgets.BsButtonColumn',
                    'template'=>'{delete}{update}',
                    'buttons'=>[
                        'update'=>[
                            'url'=>'Yii::app()->createUrl("client/update", array("id"=>$data->id))'
                        ],
                        'delete'=>[
                            'url'=>'Yii::app()->createUrl("client/delete", array("id"=>$data->id,"ajax"=>"client-grid" ))',
                        ]
                    ]
                ),
            ),
        ));
        ?>
    </div>
</div>